apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../microservices-demo/kubernetes-manifests/productcatalogservice.yaml
- ../../../../microservices-demo/kubernetes-manifests/loadgenerator.yaml
namespace: ms-demo