apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    apiVersion: v1
    kind: Node
    metadata:
      name: minikube
    spec:
      taints:
      - effect: NoSchedule
        key: key1
        value: value1
resources:
- ../../resources/node.yaml
namespace: ms-demo